### ISSUE TITLE
I am a fan of your YouTube channel and I would like to know what keyboard and mouse you are using

### ISSUE THREAD

**Issue by geeeeeeeek** [techleadhd/XDelete#3]
I am a fan of your YouTube channel and I would like to know what keyboard and mouse you are using

**Comment by techleadhd** [comment]
Yeah, a lot of my gear is here https://www.amazon.com/shop/techlead/list/UVRWWQKBFRR
I use the Razer Basilisk V3 Mouse, but would also suggest the MX Master 3S... try it out at the store to figure out what you like, but if you travel much then the Razer would be less bulky at a cost of the MX's superior scrollwheel. And a variety of keyboards (Keychron Q1 Max, Razer Deathadder, IQUNIX F97, Logitech G915 TKL, etc)
